### PR TITLE
elements with classes like is-active should have an aria attribute

### PR DESCRIPTION
**Pull request by mgrsskls**
Elements with any of the following classes

- `is-active`
- `active`
- `is-current`
- `current`
- `is-selected`
- `selected`
- `…--active`
- `…--current`
- `…--selected`

should most likely have a `aria-current` or `aria-selected` attribute.

This is only a warning, since there might be cases where this does not apply.

### CODE REVIEW

**Comment by mvsde** [comment]
Probably a bit rarer, but elements with these classes should have an `aria-busy` attribute:

* `is-busy`
* `…--busy`

[Specification for `aria-busy`](https://www.w3.org/TR/wai-aria/#aria-busy)

**Comment by mgrsskls** [comment]
@mvsde Not sure if I get your point. Why would someone set a class like `is-busy`? I have never seen that :)

**Comment by mvsde** [comment]
@mgrsskls This can be used for something like skeleton loaders.

Vuetify has an example: https://vuetifyjs.com/en/components/skeleton-loaders/. They use a different class naming scheme (`…--is-loading`), but it is the same idea.

**Comment by mgrsskls** [comment]
But `is-busy` is not really a common class, I would say? The idea was that classes like `is-active` are used quite often to e.g. highlight active links in a menu, but instead `aria-current` could be used. I don't think that applies to `is-busy` … ?

**Comment by mvsde** [comment]
Yes, that’s true 👍🏻 I may have misunderstood the original purpose of the highlighting. I thought it should include all aria-attributes that can possibly have a CSS class associated with them.

**Pull request merged**
